# Generated by Django 5.2.7 on 2025-10-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name']},
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service price in NPR', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='processing_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days to process the service'),
        ),
    ]
