# Generated by Django 5.2.7 on 2025-10-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_options_service_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in NPR', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('E-Sewa', 'E-Sewa'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Credit/Debit Card', 'Credit/Debit Card')], default='Cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID from payment gateway', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes', null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.userapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
