# Generated by Django 5.2.7 on 2025-10-12 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='userdocument',
            name='document_name',
            field=models.CharField(default='Document', help_text='Name of the document', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.userapplication'),
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('required_doc_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(help_text="Name of the required document (e.g., 'Citizenship Certificate')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional instructions for this document')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this document mandatory?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='core.service')),
            ],
            options={
                'ordering': ['service', 'document_name'],
                'unique_together': {('service', 'document_name')},
            },
        ),
        migrations.AddField(
            model_name='userdocument',
            name='required_document',
            field=models.ForeignKey(blank=True, help_text='Link to the required document type', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.requireddocument'),
        ),
    ]
