# Generated by Django 5.2.7 on 2025-10-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('settings_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for payments (e.g., merchant@paytm)', max_length=100, null=True)),
                ('upi_number', models.CharField(blank=True, help_text='UPI Mobile Number', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank Name', max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank Account Number', max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Account Holder Name', max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC/SWIFT Code', max_length=20, null=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='QR Code Image for UPI Payment', null=True, upload_to='payment_qr/')),
                ('esewa_merchant_id', models.CharField(blank=True, help_text='E-Sewa Merchant ID', max_length=100, null=True)),
                ('khalti_public_key', models.CharField(blank=True, help_text='Khalti Public Key', max_length=100, null=True)),
                ('payment_instructions', models.TextField(blank=True, help_text='General payment instructions for users', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link_sent',
            field=models.BooleanField(default=False, help_text='Whether payment details have been sent to user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link_sent_at',
            field=models.DateTimeField(blank=True, help_text='When payment details were sent', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('E-Sewa', 'E-Sewa'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Credit/Debit Card', 'Credit/Debit Card'), ('UPI', 'UPI')], default='Cash', max_length=20),
        ),
    ]
