# Generated by Django 5.2.7 on 2025-10-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymentsettings_payment_payment_link_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='esewa_merchant_id',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='khalti_public_key',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='payment_instructions',
        ),
    ]
