# Generated by Django 5.2.7 on 2025-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_paymentsettings_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('QR', 'QR Code')], default='Cash', max_length=20),
        ),
    ]
