# Generated by Django 5.2.7 on 2025-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='userapplication',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='finaldocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Payment amount in NPR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether payment details have been sent to user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('QR', 'QR Code')], db_index=True, default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='External transaction ID from payment gateway', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(blank=True, db_index=True, help_text='UPI ID for payments (e.g., merchant@paytm)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_number',
            field=models.CharField(blank=True, db_index=True, help_text='UPI Mobile Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='document_name',
            field=models.CharField(db_index=True, help_text="Name of the required document (e.g., 'Citizenship Certificate')", max_length=200),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='is_mandatory',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this document mandatory?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Service price in NPR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='processing_days',
            field=models.PositiveIntegerField(db_index=True, default=7, help_text='Number of days to process the service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_name',
            field=models.CharField(db_index=True, default='Document', help_text='Name of the document', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-created_at'], name='core_announ_is_acti_de04ef_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['type', '-created_at'], name='core_announ_type_98d0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_by', '-created_at'], name='core_announ_created_ee3a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='finaldocument',
            index=models.Index(fields=['application', '-uploaded_at'], name='core_finald_applica_c7d271_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', '-created_at'], name='core_paymen_payment_94fed5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'payment_status'], name='core_paymen_payment_bac361_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='core_paymen_payment_acb694_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='core_paymen_transac_e8c2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsettings',
            index=models.Index(fields=['is_active', '-created_at'], name='core_paymen_is_acti_b548cf_idx'),
        ),
        migrations.AddIndex(
            model_name='requireddocument',
            index=models.Index(fields=['service', 'is_mandatory'], name='core_requir_service_5ceae5_idx'),
        ),
        migrations.AddIndex(
            model_name='requireddocument',
            index=models.Index(fields=['-created_at'], name='core_requir_created_239087_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_name', 'price'], name='core_servic_service_8c3ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='core_servic_created_cf26f0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='core_user_usernam_f10d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='core_user_role_f6ec93_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='core_user_created_51fdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='userapplication',
            index=models.Index(fields=['user', 'status'], name='core_userap_user_id_56caf7_idx'),
        ),
        migrations.AddIndex(
            model_name='userapplication',
            index=models.Index(fields=['service', 'status'], name='core_userap_service_8cadaf_idx'),
        ),
        migrations.AddIndex(
            model_name='userapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='core_userap_status_5fc434_idx'),
        ),
        migrations.AddIndex(
            model_name='userapplication',
            index=models.Index(fields=['-updated_at'], name='core_userap_updated_54cc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['application', '-uploaded_at'], name='core_userdo_applica_69ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['required_document', '-uploaded_at'], name='core_userdo_require_07a3b3_idx'),
        ),
    ]
