# Generated by Django 5.2.7 on 2025-10-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_database_indexes_optimization'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovScheme',
            fields=[
                ('scheme_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name of the government scheme', max_length=200)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Employment', 'Employment'), ('Housing', 'Housing'), ('Business', 'Business'), ('Social Welfare', 'Social Welfare')], db_index=True, help_text='Category of the scheme', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the scheme')),
                ('eligibility', models.TextField(help_text='Eligibility criteria for the scheme')),
                ('benefits', models.TextField(help_text='Benefits provided by the scheme')),
                ('documents', models.JSONField(blank=True, default=list, help_text='List of required documents (JSON array)')),
                ('how_to_apply', models.JSONField(blank=True, default=list, help_text='Steps to apply for the scheme (JSON array)')),
                ('official_website', models.URLField(blank=True, help_text='Official website URL', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the scheme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='core_govsch_is_acti_5442c9_idx'), models.Index(fields=['category', 'is_active'], name='core_govsch_categor_addfda_idx'), models.Index(fields=['name'], name='core_govsch_name_b17791_idx')],
            },
        ),
    ]
