# Generated by Django 5.2.7 on 2025-10-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_database_indexes_optimization'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovScheme',
            fields=[
                ('scheme_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Employment', 'Employment'), ('Housing', 'Housing'), ('Business', 'Business'), ('Social Welfare', 'Social Welfare')], db_index=True, default='Social Welfare', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('how_to_apply', models.JSONField(blank=True, default=list)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='core_govsch_is_acti_5442c9_idx'), models.Index(fields=['category', 'is_active'], name='core_govsch_categor_addfda_idx')],
            },
        ),
    ]
