# Generated by Django 5.2.7 on 2025-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_govscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay')], db_index=True, default='Razorpay', max_length=20),
        ),
    ]
