# Generated by Django 5.2.7 on 2025-11-01 22:46

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_unique_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GopinathApplication',
            fields=[
                ('app_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhaar', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/photos/', validators=[core.models.validate_file])),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('college_address', models.TextField(blank=True)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('study_year', models.CharField(blank=True, max_length=50)),
                ('college_id_number', models.CharField(blank=True, max_length=100)),
                ('college_id_card', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/college_id/', validators=[core.models.validate_file])),
                ('current_address', models.TextField(blank=True)),
                ('native_place', models.CharField(blank=True, max_length=255)),
                ('residence_type', models.CharField(blank=True, max_length=50)),
                ('residence_name_address', models.TextField(blank=True)),
                ('ration_card_number', models.CharField(blank=True, max_length=100)),
                ('ration_card_type', models.CharField(blank=True, max_length=50)),
                ('veg_nonveg', models.CharField(blank=True, max_length=20)),
                ('ration_card_file', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/ration_card/', validators=[core.models.validate_file])),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/bank_passbook/', validators=[core.models.validate_file])),
                ('aadhaar_file', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/aadhaar/', validators=[core.models.validate_file])),
                ('fee_residence_proof', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/proofs/', validators=[core.models.validate_file])),
                ('last_marksheet', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/marksheets/', validators=[core.models.validate_file])),
                ('declaration', models.BooleanField(default=False)),
                ('signature', models.FileField(blank=True, null=True, upload_to='schemes/gopinath/signatures/', validators=[core.models.validate_file])),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Submitted', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_gopina_user_id_5234bb_idx'), models.Index(fields=['mobile', 'aadhaar'], name='core_gopina_mobile_5b7dcf_idx'), models.Index(fields=['-submitted_at'], name='core_gopina_submitt_bd9fc0_idx')],
            },
        ),
    ]
