"""
Django settings for sewa_portal project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv

# Load .env for local development
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------
# SECURITY CONFIGURATION
# ------------------------
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'unsafe-development-secret')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

raw_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS')
if raw_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in raw_allowed_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'cgjbcsc.onrender.com',
        'cgjbcsc.netlify.app',
    ]

# ------------------------
# APPLICATIONS
# ------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'rest_framework',
    'storages',  # Django-storages for custom backends
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # after SecurityMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sewa_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'core.User'
WSGI_APPLICATION = 'sewa_portal.wsgi.application'

# ------------------------
# DATABASE CONFIGURATION
# ------------------------
# DATABASE CONFIGURATION
# Prefer an explicit DATABASE_URL in the environment (production). If it's not
# set, fall back to a local SQLite database for development to avoid attempting
# DNS resolution of a production host during local runs.
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parse a Postgres (or other) URL from the environment
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Local development fallback
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ------------------------
# REST FRAMEWORK
# ------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# ------------------------
# PASSWORD VALIDATION
# ------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------
# INTERNATIONALIZATION
# ------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------
# STATIC & MEDIA FILES
# ------------------------
# STATIC & MEDIA FILES
# ------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE moved to STORAGES setting below

# ------------------------
# DROPBOX STORAGE CONFIGURATION (NO LOCAL STORAGE)
# ------------------------
# All files are stored in Dropbox - no local media folder is used
# Database stores only the file path, actual files are in Dropbox
DROPBOX_ACCESS_TOKEN = os.environ.get(
    'DROPBOX_ACCESS_TOKEN',
    'sl.u.AGAPwfTF8cP4412vk421wn0eMxTsR1512HfaXmqvKLiQlg7vN_V4qTqC7DmQQLrz7thODRdKbhkGQ0wJIw0JhdMfE1DygcwwNl68BdheWWQYhudj4GjqC1WOrGwLxEzmP68t93BJgX5GoMfuMxhtvUCavCHOLPGt7hNog_HOPrHcyw4SccPoNTJavp5z0iM2eIVhNFq8Jt6GA22ipYeGOFJqZc6FtK9NDPyD9PXycF1iL8aC4cfX2refx0wm5e-mN0wRaETtSDgif1CGJ72vfvhmCo3IOWfuw_BOMQphes8Y-Cb6JN3ynYEf6iY11728TWe_R7x-US6uUKs4djJoMpVmaanrx6vroWSPdg8PsTAAfSIwQ5O1tXl7JuOz84aO_8me8rB8Y_UZIom-G6DjomUQGT9GrG_J40gYgu6XyI_3cWSNs7uMGQwhYOaoXZ5Ua2Go2wP31N9ssaNKcUU5sOGGGKhXV9Htm1onIeSdeik8OxC4AX19xpLXShg6dXZK0yL3qY4igOU87RC6gL7G_hu5Wck_5bjiAG9Za862ogCgrzdhx_0HHrZwYg2lDTJ2JA7q4ZCM6Ekx7f8AdPfc1HzMuRV2jjOzBkmO-ok0R3AK1zbFdsXgZeOhbrUTHf4YyzhN96iGSg0PP5bV7Xd8Lwshxs_9vO3JIazRRgtwDZB8cQibgov7NXK0BZlGGB1u8XDKvsd5kh-VeSJ1ON0i5QLnjYGYxA2Yb8Xuw_b2wTV4tlLg5qpmtU7bVn6Kp9vCzP5Df28DdTP1ZJxecgfvAl5dR_BexMgv3qU84EpBT3CtqEKaNNTh5Xr68cW7k7BzyihlaipFgHAZvAu7TXvUdDfFOhSRKQMxa7A87ANclmsU6EJos3XwwQ_6IgaGqVoUYUjhN2OC4aDY6lZX0LvfaTUrQ68DTOaDESrWJFqTp8oRkbJimBVLQGu_Wv1Q-uQ9Jvkviy2vPkhsntXSZYw2o9XYxCup5N1nejILTu1aBQZvofd8uCfTkOi0cU3gsc4ov51yPMEajtYZk00hGpmKwBz_7q_wX-3tH3uA1CktL5MBqC3FQmoNGJNtNH6R5hfEn6ETxYDbOzE78sMEmiGQGW_HTsyyVn8WinEANNWMBhbuIqOup7KMQVxBoGUPG7bE-OjnkBNwLTCd_dGGlvOh9o9hBI4S8Z3M1U0vlcUQeykDvxgJ_u4p_xcb6RGgZOtIu3hZjHBfpGvelkV3vyEP9sMJQyLONPuGaQfptWZDR0kPmSDRVALO7StWCbzDD_cWlu3bk2nKG23RbwH5bx86rBVsZT9HpkTkahclRwgL7K0LFJz4FHCqV7kUrFN0rtSADiHUB3luKC0UDfPrYsm4AklvEnvEQpmlBO9AqwzjxpDtV2tWqDDYc7xq60iFP_1likD50yQRv5zvv90QTq0lh3brUAtcwl1F_nlW_SGR96kRmg'
)
DROPBOX_ROOT_PATH = os.environ.get('DROPBOX_ROOT_PATH', '/sewa_portal')
DROPBOX_TIMEOUT = int(os.environ.get('DROPBOX_TIMEOUT', '100'))

# Django 4.2+ uses STORAGES setting (replaces DEFAULT_FILE_STORAGE)
STORAGES = {
    "default": {
        "BACKEND": "core.storage_backends.DropboxStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# MEDIA_URL is not used - files are served directly from Dropbox via temporary URLs
# No MEDIA_ROOT defined - no local media folder will be created


# ------------------------
# EMAIL CONFIGURATION
# ------------------------
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Sewa Portal <{EMAIL_HOST_USER}>')

# ------------------------
# SIMPLE JWT CONFIGURATION
# ------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}

# ------------------------
# CORS CONFIGURATION
# ------------------------
raw_cors = os.environ.get('CORS_ALLOWED_ORIGINS')
if raw_cors:
    CORS_ALLOWED_ORIGINS = [u.strip() for u in raw_cors.split(',') if u.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # Vite dev server
        "http://localhost:3000",  # Alternative frontend port
        "http://127.0.0.1:5173",  # IPv4 localhost
        "http://127.0.0.1:3000",
        "https://cgjbcsc.netlify.app"  # Production frontend
    ]
CORS_ALLOW_CREDENTIALS = True

# ------------------------
# DEFAULT AUTO FIELD
# ------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

